budget/accounts/urls.py
from django.urls import path
from .views import *
from .decorators import check_recaptcha

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', check_recaptcha(RegisterView.as_view()), name='register'),
]

budget/budget/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter
import api.views as api
from rest_framework.authtoken import views

router = DefaultRouter()
router.register('headers', api.HeaderModelViewSet)
router.register('categories', api.CategoryModelViewSet)
router.register('subcategories', api.SubcategoryModelViewSet)
router.register('transactions', api.TransactionModelViewSet)
router.register('ma_list', api.MoneyAccountListViewSet)
router.register('total_balance', api.TotalBalanceModelViewSet)
router.register('total_balance_per_account', api.TotalBalancePerAccountModelViewSet)
router.register('plain_operations', api.PlainOperationModelViewSet)
router.register('money_accounts', api.MoneyAccountModelViewSet)
router.register('report', api.ReportViewSet)
router.register('ex_report', api.ExcludeReportViewSet)
router.register('statistic', api.StatisticViewSet)
router.register('budget', api.BudgetModelViewSet)
router.register('budget_detail', api.BudgetDetailModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('transactionapp/', include('transactionapp.urls', namespace='transactions')),
    path('maapp/', include('maapp.urls', namespace='money_accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('report/', ReportView.as_view(), name='report'),
    path('generated_report/', GeneratedReportView.as_view(), name='generated_report'),
    path('generated_report/<date>', DetailReportView.as_view(), name='detail_report'),
    path('settings', SettingsView.as_view(), name='settings'),
    path('settings/statistic/', StatisticView.as_view(), name='statistic'),
    path('settings/filter/', FilterSettingsView.as_view(), name='filter'),
    path('settings/generated_filter/', GeneratedFilterView.as_view(), name='generated_filter'),
    path('settings/last20/', Last20View.as_view(), name='last20'),
    path('budget/budget_list/', BudgetListView.as_view(), name='budget_list'),
    path('budget/create/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/detail/<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/update/<int:pk>/', BudgetEditView.as_view(), name='budget_edit'),
    path('budget/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget_delete'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/api-token-auth/', views.obtain_auth_token),
    ]

budget/maapp/urls.py
from django.urls import path
from .views import *
from transactionapp.views import TransactionsListView

app_name = 'maapp'

urlpatterns = [
    path('', AccountsListView.as_view(), name='accounts'),
    path('hide/<int:pk>', AccountsListView.hide_control, name='hide'),
    path('create/', AccountCreateView.as_view(), name='create_account'),
    path('account_<int:pk>/<int:year>/<int:month>/', TransactionsListView.as_view(), name='detail_account'),
]

budget/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    error_messages = {
        'duplicate_username': 'Пользователь с таким именем уже существует',
        'duplicate_email': 'Пользователь с таким адресом уже существует',
    }

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User._default_manager.get(username=username)
            raise forms.ValidationError(
                self.error_messages['duplicate_username'],
                code='duplicate_username',
            )
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            User._default_manager.get(email=email)
            raise forms.ValidationError(
                self.error_messages['duplicate_email'],
                code='duplicate_email',
            )
        except User.DoesNotExist:
            return email

budget/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, TemplateView

from budget import settings
from .forms import UserRegisterForm


class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')
    form_class = UserRegisterForm
    success_message = "Your profile was created successfully"

    def form_valid(self, form):
        if self.request.recaptcha_is_valid:
            self.object = form.save()
            return super().form_valid(form)
        return self.render_to_response(self.get_context_data(form=form))

    @receiver(post_save, sender=User)
    def user_to_inactive(sender, instance, created, update_fields, **kwargs):
        if created:
            instance.is_active = False
            mail_subject = 'Activate budget account.'
            message = render_to_string('accounts/email_admin_activation_body.html', {
                'username': instance.username,
                'email': instance.email,
            })
            to_email = settings.EMAIL_HOST_USER
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()


class LoginView(TemplateView):
    success_url = reverse_lazy('index')
    template_name = 'accounts/login.html'

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy(settings.LOGIN_REDIRECT_URL))
            else:
                return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))
        else:
            try:
                user_form = User.objects.get(username=request.POST['username'])
                if not user_form.is_active:
                    messages.error(request, 'Пользователь не активирован')
            except:
                messages.error(request, 'Неверное имя пользователя или пароль')
            return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))

budget/accounts/templates/accounts/email_admin_activation_body.html
{% autoescape off %}
Зарегистрирован пользователь {{ username }}, с адресом почты {{ email }}
{% endautoescape %}

budget/accounts/templates/accounts/login.html
{% extends 'budget/base.html' %}
{% load static %}
{% block content %}
<body>
 <br>
    <br>
    <div class="container no_footer">
        <div class="title__single">Вход в систему</div>
        <br>
        <form method="post">
            {% csrf_token %}
            <input id="id_username" type="text" name="username" class="form__control" placeholder="Логин" required>
            <br>
            <input type="password" name="password" class="form__control" placeholder="Пароль" required>
            <br>
            <br>
            <div class="tr__upper tr__upper__left">
                <input type="submit" class="btn btn__green" value="Войти">
                <input type="button" class="btn btn__green"
                        onclick="window.location.href='{% url 'accounts:register' %}';" value="Регистрация" />

            </div>
        </form>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
</body>
{% endblock %}

budget/accounts/templates/accounts/register.html
{% extends 'budget/base.html' %}
{% load static %}
{% block content %}
<body>
 <br>
    <br>
    <div class="container no_footer">
        <div class="title__single">Регистрация нового пользователя</div>
        <br>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="username" class="form__control" placeholder="Логин" required>
            <br>
            <input type="email" name="email" class="form__control" placeholder="Электронная почта" required>
            <br>
            <input id="id_password1" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" type="password" name="password1" class="form__control" placeholder="Пароль" onkeyup='check();' title="Должен содержать как минимум одну цифру, одну заглавную и строчную букву и быть минимум 8 символов" required>
            <br>
            <input id="id_password2" type="password" name="password2" class="form__control" placeholder="Подтверждение пароля" onkeyup='check();' required>
            <br>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="form-group g-recaptcha" data-sitekey="6LcH8hIcAAAAAMd4wyt_eWSE0FgYTDN4jVUPEtMA"></div>
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
            <br>
            <div class="tr__upper tr__upper__left">
                <input id="id_submit" type="submit" class="btn btn__green" value="Зарегистрироваться">
            </div>
        </form>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {% endif %}
    </div>
 <script>
     const check = function () {
         if (document.getElementById('id_password1').value ===
             document.getElementById('id_password2').value) {
             document.getElementById('id_password1').style.border = 'None'
             document.getElementById('id_password2').style.border = 'None'
             document.getElementById('id_submit').disabled = false;
         } else {
             document.getElementById('id_password1').style.border = '2px solid red'
             document.getElementById('id_password2').style.border = '2px solid red'
             document.getElementById('id_submit').disabled = true;
         }
     };
 </script>
 <script>

 </script>
</body>
{% endblock %}