budget/budget/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter
import api.views as api
from rest_framework.authtoken import views

router = DefaultRouter()
router.register('headers', api.HeaderModelViewSet)
router.register('categories', api.CategoryModelViewSet)
router.register('subcategories', api.SubcategoryModelViewSet)
router.register('transactions', api.TransactionModelViewSet)
router.register('ma_list', api.MoneyAccountListViewSet)
router.register('total_balance', api.TotalBalanceModelViewSet)
router.register('total_balance_per_account', api.TotalBalancePerAccountModelViewSet)
router.register('plain_operations', api.PlainOperationModelViewSet)
router.register('money_accounts', api.MoneyAccountModelViewSet)
router.register('report', api.ReportViewSet)
router.register('ex_report', api.ExcludeReportViewSet)
router.register('statistic', api.StatisticViewSet)
router.register('budget', api.BudgetModelViewSet)
router.register('budget_detail', api.BudgetDetailModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('transactionapp/', include('transactionapp.urls', namespace='transactions')),
    path('maapp/', include('maapp.urls', namespace='money_accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('report/', ReportView.as_view(), name='report'),
    path('generated_report/', GeneratedReportView.as_view(), name='generated_report'),
    path('generated_report/<date>', DetailReportView.as_view(), name='detail_report'),
    path('settings', SettingsView.as_view(), name='settings'),
    path('settings/statistic/', StatisticView.as_view(), name='statistic'),
    path('settings/filter/', FilterSettingsView.as_view(), name='filter'),
    path('settings/generated_filter/', GeneratedFilterView.as_view(), name='generated_filter'),
    path('settings/last20/', Last20View.as_view(), name='last20'),
    path('budget/budget_list/', BudgetListView.as_view(), name='budget_list'),
    path('budget/create/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/detail/<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/update/<int:pk>/', BudgetEditView.as_view(), name='budget_edit'),
    path('budget/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget_delete'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/api-token-auth/', views.obtain_auth_token),
    ]

budget/maapp/urls.py
from django.urls import path
from .views import *
from transactionapp.views import TransactionsListView

app_name = 'maapp'

urlpatterns = [
    path('', AccountsListView.as_view(), name='accounts'),
    path('hide/<int:pk>', AccountsListView.hide_control, name='hide'),
    path('create/', AccountCreateView.as_view(), name='create_account'),
    path('account_<int:pk>/<int:year>/<int:month>/', TransactionsListView.as_view(), name='detail_account'),
]

budget/transactionapp/urls.py
from django.urls import path
from .views import *

app_name = 'transactionapp'

urlpatterns = [
    path('create/', TransactionCreateView.as_view(), name='transaction_create'),
    path('update/<int:pk>/', TransactionUpdateView.as_view(), name='transaction_update'),
    path('delete/<int:pk>/', TransactionDeleteView.as_view(), name='transaction_delete'),
    path('autoform/<header_name>/', TransactionCreateView.transaction_autoform, name='tr_autoform'),
    path('', TransactionsListView.as_view(), name='transactions'),
    path('<int:year>/<int:month>/', TransactionsListView.as_view(), name='page'),
    path('transfer/creat/e', TransferCreateView.as_view(), name='transfer_create'),
    path('transfer/update/<int:transfer_id>/', TransferUpdateView.as_view(), name='transfer_update'),
    path('transfer/delete/<int:transfer_id>/', TransferDeleteView.as_view(), name='transfer_delete'),
    path('plainoperations/', PlainOperationsListView.as_view(), name='plain_operations'),
    path('plainoperations/update/<int:pk>/', PlainOperationUpdateView.as_view(), name='plain_operation_update'),
    path('plainoperations/delete/<int:pk>/', PlainOperationDeleteView.as_view(), name='plain_operation_delete'),
]

budget/transactionapp/forms.py
from django import forms
from .models import Transaction, PlainOperation


# class TransactionForm(forms.ModelForm):
#     class Meta:
#         model = Transaction
#         fields = ('operation_date', 'operation_summ', 'account', 'header', 'category', 'subcategory', 'comment')
#
#     def __init__(self, *args, **kwargs):
#         super(TransactionForm, self).__init__(*args, **kwargs)


# class PlainOperationForm(forms.ModelForm):
#     class Meta:
#         model = PlainOperation
#         fields = ('operation_date', 'operation_summ', 'header',
#                   'category', 'subcategory', 'comment', 'period', 'quantity')
#
#     def __init__(self, *args, **kwargs):
#         super(PlainOperationForm, self).__init__(*args, **kwargs)

budget/transactionapp/views.py
from datetime import datetime
from maapp.models import MoneyAccount
from budget.models import Header, Category, Subcategory
from .models import Transaction, PlainOperation, Transfer, TotalBalance, TotalBalancePerAccount
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.dates import MonthArchiveView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.db.models import Count
from django.db.models import Q


class PlainOperationsListView(ListView):
    template_name = "transactionapp/plainoperations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'плановые операции'
        return context

    def get_queryset(self):
        queryset = []
        queryset_element = {}
        source_queryset = PlainOperation.objects.all()
        for el in source_queryset:
            transactions_array = Transaction.objects.filter(plain_id=el.pk).order_by('operation_date')
            queryset_element['id'] = el.pk
            queryset_element['header'] = el.header
            queryset_element['category'] = el.category
            queryset_element['subcategory'] = el.subcategory
            queryset_element['summ'] = el.operation_summ
            if len(transactions_array) != 0:
                queryset_element['curr_date'] = transactions_array.first().operation_date
                queryset_element['end_date'] = transactions_array.last().operation_date
                queryset_element['disabled_status'] = 0
            else:
                queryset_element['curr_date'] = "--"
                queryset_element['end_date'] = "--"
                queryset_element['disabled_status'] = 1
            queryset.append(queryset_element)
            queryset_element = {}
        return queryset


class PlainOperationUpdateView(UpdateView):
    model = PlainOperation
    template_name = 'transactionapp/plainoperation.html'
    fields = '__all__'
    success_url = reverse_lazy('transactionapp:plain_operations')

    def setup(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        self.transactions_array = Transaction.objects.filter(plain_id=self.kwargs['pk']).order_by('operation_date')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        period_names = {'once': 'Разовая', 'daily':'Ежедневная', 'monthly':'Ежемесячная'}
        context['title'] = 'плановая/редактирование'
        context['period_name'] = period_names[self.get_object().period]

        if len(self.transactions_array) != 0:
            context['start_date'] = str(self.transactions_array.first().operation_date)
            context['end_date'] = str(self.transactions_array.last().operation_date)
        else:
            context['start_date'] = datetime.today().strftime('%Y-%m-%d')
            context['end_date'] = datetime.today().strftime('%Y-%m-%d')
        return context

    def post(self, request, **kwargs):
        self.transactions_array.delete()
        request.POST = request.POST.copy()
        request.POST['header'], created = Header.objects.get_or_create(
            name=request.POST['header'].lstrip().rstrip().capitalize()
        )
        request.POST['category'], created = Category.objects.get_or_create(
            name=request.POST['category'].lstrip().rstrip().capitalize()
        )
        request.POST['subcategory'], created = Subcategory.objects.get_or_create(
            name=request.POST['subcategory'].lstrip().rstrip().capitalize()
        )
        # request.POST['header'] = Header.add_header_to_transaction(request.POST['header'])
        # request.POST['category'] = Category.add_category_to_transaction(request.POST['category'])
        # request.POST['subcategory'] = Subcategory.add_subcategory_to_transaction(request.POST['subcategory'])
        if request.POST['operation_type'] == 'out':
            operation_summ = float(request.POST['operation_summ']) * -1
        else:
            operation_summ = float(request.POST['operation_summ'])
        request.POST['operation_summ'] = operation_summ
        if request.POST['period'] != 'once':
            request.POST['quantity'] = PlainOperation.quantity_count(request.POST['operation_date'],
                                                                     request.POST['trip-end'],
                                                                     request.POST['period'],
                                                                     request.POST['count'])
        else:
            request.POST['quantity'] = 1
        return super(PlainOperationUpdateView, self).post(request, **kwargs)


class PlainOperationDeleteView(DeleteView):
    model = PlainOperation
    success_url = reverse_lazy('transactions:plain_operations')

    def setup(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        self.transactions_array = Transaction.objects.filter(plain_id=self.kwargs['pk']).order_by('operation_date')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.transactions_array.delete()
        return self.delete(request, *args, **kwargs)


class TransactionsListView(MonthArchiveView):
    date_field = "operation_date"
    allow_future = True
    template_name = "transactionapp/transactions.html"
    month_format = '%m'
    allow_empty = True

    # def setup(self, request, *args, **kwargs):
    #     self.request = request
    #     self.args = args
    #     self.kwargs = kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'транзакции'
        if 'pk' in self.kwargs:
            # context['total'] = Transaction.get_total_balance(self.kwargs['pk'])
            context['account'] = self.kwargs['pk']
            total = TotalBalancePerAccount.objects.\
                filter(account=self.kwargs['pk'],
                       operation_date__year=self.kwargs['year'],
                       operation_date__month=self.kwargs['month']).\
                values_list('operation_date', 'total')
        else:
            # context['total'] = Transaction.get_total_balance()
            total = TotalBalance.objects.\
                filter(operation_date__year=self.kwargs['year'],
                       operation_date__month=self.kwargs['month']).\
                values_list('operation_date', 'total')
        context['total'] = {el[0].strftime("%d-%m-%Y"): float(el[1]) for el in total}
        # print(context['new_total'])
        # print(context['total'])
        return context

    def get_queryset(self):
        if 'pk' in self.kwargs:
            return Transaction.objects.\
                select_related('header', 'category', 'subcategory', 'account', 'plain_id').\
                filter(account=self.kwargs['pk'], operation_date__year=self.kwargs['year'], operation_date__month=self.kwargs['month']).\
                order_by('operation_date', '-updated')
        else:
            return Transaction.objects.\
                select_related('header', 'category', 'subcategory', 'account', 'plain_id').\
                filter(operation_date__year=self.kwargs['year'], operation_date__month=self.kwargs['month']).\
                order_by('operation_date', '-updated')


class TransactionCreateView(CreateView):
    model = Transaction
    template_name = 'transactionapp/transaction.html'
    fields = ('operation_date', 'operation_summ', 'account', 'header', 'category', 'subcategory', 'comment')
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'транзакция/создание'
        # context['money_accounts'] = MoneyAccount.objects.all().order_by('name')
        context['headers'] = Header.objects.all()
        context['categories'] = Category.objects.all().order_by('name')
        context['subcategories'] = Subcategory.objects.all().order_by('name')
        context['date'] = datetime.today().strftime('%Y-%m-%d')
        if self.request.META.get('HTTP_REFERER'):
            if 'transactionapp/create' in self.request.META.get('HTTP_REFERER'):
                context['date'] = Transaction.get_last_transaction().operation_date.strftime('%Y-%m-%d')
                context['default_account'] = Transaction.get_last_transaction().account
        group_accounts = list(Transaction.objects.select_related('account').
                              filter(~Q(account=None)).
                              values('account', 'account__name').
                              annotate(count=Count('account__name')).order_by('-count'))
        accounts = list(MoneyAccount.objects.all().values('pk', 'name').order_by('name'))
        temp_group_accounts = [{'pk': el['account'], 'name': el['account__name']} for el in group_accounts]
        temp_accounts = [{'pk': el['pk'], 'name': el['name']} for el in accounts]
        for el in temp_accounts:
            if el not in temp_group_accounts:
                temp_group_accounts.append(el)
        context['money_accounts'] = temp_group_accounts
        return context

    def post(self, request, **kwargs):
        request.POST = request.POST.copy()
        if request.POST['operation_type'] == 'out':
            operation_summ = float(request.POST['operation_summ']) * -1
        else:
            operation_summ = float(request.POST['operation_summ'])
        request.POST['header'], created = Header.objects.get_or_create(

budget/transactionapp/templates/transactionapp/plainoperation.html
{% extends 'budget/base.html' %}
{% load static %}
{% load tr_tags %}
{% block content %}
{% load l10n %}
<body>
<div class="container">
    <div class="title__single">Планируемая операция</div>
    <br>
    <form method="post">
    {% csrf_token %}
        <div class="tr__upper">
            <select class="form__select form__sm row__2" name="operation_type">
                        {% if object.operation_summ > 0 %}
                            <option selected value="in">Приход</option>
                        {% endif %}
                        {% if object.operation_summ < 0 %}
                            <option selected value="out">Расход</option>
                        {% endif %}
            </select>
            <select name="period" class="form__select form__sm row__2" id="period">
                <option selected value="{{ object.period }}">{{ period_name }}</option>
            </select>
        </div>
        <div class="tr__upper">
            <input class="form__control form__sm row__2" type="date" id="start" name="operation_date"
                   value="{{ start_date }}">

            <input class="form__control form__sm row__2" type="date" id="end"
                   name="trip-end"
                   value="{{ end_date }}" {% if period == "once" %}disabled{% endif %}>
        </div>
        <input type="number" name="count" class="form__control form__sm"
               value="{{ object.count }}">
        <hr class="top__hr">
        <input type="number" step="0.01" name="operation_summ" class="form__control" placeholder="Сумма"
               value="{% localize off %}{{ object.operation_summ|abs }}{% endlocalize %}"
               required>
        <br>
        <input type="text" name="header" class="form__control" value="{{ object.header }}" readonly>
        <br>
        <input type="text" name="category" class="form__control" value="{{ object.category }}" readonly>
        <br>
        <input type="text" name="subcategory" class="form__control" value="{{ object.subcategory }}" readonly>
        <br>
        <input type="text" name="comment" class="form__control" placeholder="Комментарий"
               value="{{ plain_operation.comment }}">
        <br>
        <div class="tr__upper tr__upper__left">
            <input type="submit" class="btn btn__green" value="Отправить" id="submit">
            <input type="button" class="btn btn__red"
                   onclick="window.location.href='{% url "transactions:plain_operation_delete" object.pk %}';"
                   value="Удалить"/>
            <input type="button" class="btn btn__red" onclick="window.location.href='{% url "transactions:plain_operations" %}';"
                   value="Закрыть"/>
        </div>
    </form>
</div>
</body>
{% endblock %}

budget/transactionapp/templates/transactionapp/plainoperations.html
{% extends 'budget/base.html' %}
{% load static %}
{% load tr_tags %}
{% block content %}
{% load humanize %}
<body>
<div class="container">
    {% for object in object_list %}
    <a href="{% url 'transactionapp:plain_operation_update' object.id %}"
       class="tr__box {% if object.disabled_status == 1 %}past__color{% endif %}">
        <div class="tr__box__row">
            <div class="tr__box__row__left">{{ object.header }}</div>
            <div class="tr__box__row__right num {% if object.summ > 0 %}green__color{% else %}red__color{% endif %}">
                {{ object.summ|intcomma }}
            </div>
        </div>
        <div class="tr__box__row">
            <div class="tr__box__row__left">{{ object.category }}</div>
            <div class="tr__box__row__right">Ближ: {{ object.curr_date|date:"d-m-Y" }}</div>
        </div>
        <div class="tr__box__row">
            <div class="tr__box__row__left">{{ object.subcategory }}</div>
            <div class="tr__box__row__right">Посл: {{ object.end_date|date:"d-m-Y" }}</div>
        </div>
    </a>
    {% endfor %}
    <br>
    <br>
    <br>
    <br>
</div>
{% include 'includes/inc_main_menu.html' %}
</body>
{% endblock %}

budget/transactionapp/templates/transactionapp/transactions.html
{% extends 'budget/base.html' %}
{% load static %}
{% load tr_tags %}
{% block content %}
{% load humanize %}
<body>
<div class="container">
    {% for object in object_list %}
        {% if request.resolver_match.url_name != 'last20' %}
        {% ifchanged object.operation_date %}
            <div class="total__box" id="{{ object.operation_date|date:"d-m-Y" }}">
                <div class="t__left">
                    <div class="t__int">{{ object.operation_date|date:"d-m-Y" }}&nbsp;</div>
                    <div class="t__str">{{ object.operation_date|date:"D" }}</div>
                </div>
                {% if request.resolver_match.url_name == 'page' or request.resolver_match.url_name == 'detail_account'%}
                <div class="t__right">
                    <div class="t__str">Баланс:&nbsp;</div>
                    {% with date=object.operation_date|date:"d-m-Y" %}
                    <div class="t__int num {% if total|get_item:date > 0 %}green__color{% else %}red__color{% endif %}">
                        {{ total|get_item:date|intcomma }}
                    </div>
                    {% endwith %}
                </div>
                {% endif %}
            </div>
        {% endifchanged %}
        {% endif %}
        <a href="{% if object.transfer_id %}
                   {% url 'transactions:transfer_update' object.transfer_id %}
                 {% else %}
                   {% url 'transactions:transaction_update' object.pk %}
                 {% endif %}"
           class="tr__box {% if object.transfer_id %}transfer__color{% endif %} {% if object.past == 1 %}past__color{% endif %}">
            <div class="tr__box__row">
                <div><b>{% if not object.transfer_id %}{{ object.header }}{% else %}{{ object.comment }}{% endif %}</b>
                </div>
                <div class="num {% if object.operation_summ > 0 %}green__color{% else %}red__color{% endif %}">
                    {{ object.operation_summ|intcomma }}
                </div>
            </div>
            {% if not object.transfer_id %}
                <div class="tr__box__row">
                    <div>{{ object.category }}</div>
                    <div>{{ object.account }}</div>
                </div>
            {% endif %}
            <div class="tr__box__row">
                <div>
                    {% if not object.transfer_id %}{{ object.subcategory }}{% else %}{{ object.account }}{% endif %}
                </div>
                <div>{{ object.operation_date|date:"d-m-Y" }}</div>
            </div>
        </a>
    {% endfor %}
</div>
<div class="clear__block"></div>
{% include 'includes/inc_main_menu.html' %}
<script>
document.addEventListener('touchstart', handleTouchStart, false);
document.addEventListener('touchmove', handleTouchMove, false);

var xDown = null;
var yDown = null;

function getTouches(evt) {
  return evt.touches ||             // browser API
         evt.originalEvent.touches; // jQuery
}

function handleTouchStart(evt) {
    const firstTouch = getTouches(evt)[0];
    xDown = firstTouch.clientX;
    yDown = firstTouch.clientY;
};

function handleTouchMove(evt) {
    if ( ! xDown || ! yDown ) {
        return;
    }

    var xUp = evt.touches[0].clientX;
    var yUp = evt.touches[0].clientY;

    var xDiff = xDown - xUp;
    var yDiff = yDown - yUp;

    if ( Math.abs( xDiff ) > Math.abs( yDiff )) {/*most significant*/
        if ( xDiff > 0 ) {
            document.getElementById('right_arrow').click();
        } else {
            document.getElementById('left_arrow').click();
        }
    }
    /* reset values */
    xDown = null;
    yDown = null;
};
</script>
</body>
{% endblock %}

budget/transactionapp/templates/transactionapp/transfer.html
{% extends 'budget/base.html' %}
{% load static %}
{% load tr_tags %}
{% block content %}
{% load l10n %}
    <body>
    <div class="container">
        <div class="title__single">Перевод</div>
        <br>
        <form method="post">
        {% csrf_token %}
            <div class="tr__upper">
                <input class="form__control form__sm" type="date" id="start" name="trip-start"
                       value="{{ date }}">
            </div>

            <hr class="top__hr">
            <input onfocus="this.select();" type="number" step="0.01" name="summ" class="form__control"
                   placeholder="Сумма" value="{% localize off %}{{ summ }}{% endlocalize %}" required><br>
            <h4 class="select__label">Откуда</h4>
            <select name="money_account_from" class="form__select form__sm">
                <option selected value="{{ account_from.pk }}">{{ account_from.name }}</option>
                {% for el in money_accounts %}
                    <option value="{{ el.pk }}">{{ el.name }}</option>
                {% endfor %}
            </select>
            <h4 class="select__label">Куда</h4>
            <select name="money_account_to" class="form__select form__sm">
            <option selected value="{{ account_to.pk }}">{{ account_to.name }}</option>
                {% for el in money_accounts %}
                    <option value="{{ el.pk }}">{{ el.name }}</option>
                {% endfor %}
            </select>
            <br>
            <div class="tr__upper tr__upper__left">
                <input id="submit" type="submit" class="btn btn__green" value="Отправить">
                {% if request.resolver_match.url_name == 'transfer_update' %}
                    <input id="delete" type="button" class="btn btn__red"
                        onclick="window.location.href='{% url 'transactionapp:transfer_delete' transfer_id %}';" value="Удалить" />
                    {% endif %}
                <input id="close" type="button" class="btn btn__red" onclick="window.location.href='{% url 'index' %}';"
                       value="Закрыть"/>
            </div>
        </form>
    </div>
    </body>
{% endblock %}