budget/accounts/urls.py
from django.urls import path
from .views import *
from .decorators import check_recaptcha

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', check_recaptcha(RegisterView.as_view()), name='register'),
]

budget/budget/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter
import api.views as api
from rest_framework.authtoken import views

router = DefaultRouter()
router.register('headers', api.HeaderModelViewSet)
router.register('categories', api.CategoryModelViewSet)
router.register('subcategories', api.SubcategoryModelViewSet)
router.register('transactions', api.TransactionModelViewSet)
router.register('ma_list', api.MoneyAccountListViewSet)
router.register('total_balance', api.TotalBalanceModelViewSet)
router.register('total_balance_per_account', api.TotalBalancePerAccountModelViewSet)
router.register('plain_operations', api.PlainOperationModelViewSet)
router.register('money_accounts', api.MoneyAccountModelViewSet)
router.register('report', api.ReportViewSet)
router.register('ex_report', api.ExcludeReportViewSet)
router.register('statistic', api.StatisticViewSet)
router.register('budget', api.BudgetModelViewSet)
router.register('budget_detail', api.BudgetDetailModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('transactionapp/', include('transactionapp.urls', namespace='transactions')),
    path('maapp/', include('maapp.urls', namespace='money_accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('report/', ReportView.as_view(), name='report'),
    path('generated_report/', GeneratedReportView.as_view(), name='generated_report'),
    path('generated_report/<date>', DetailReportView.as_view(), name='detail_report'),
    path('settings', SettingsView.as_view(), name='settings'),
    path('settings/statistic/', StatisticView.as_view(), name='statistic'),
    path('settings/filter/', FilterSettingsView.as_view(), name='filter'),
    path('settings/generated_filter/', GeneratedFilterView.as_view(), name='generated_filter'),
    path('settings/last20/', Last20View.as_view(), name='last20'),
    path('budget/budget_list/', BudgetListView.as_view(), name='budget_list'),
    path('budget/create/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/detail/<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/update/<int:pk>/', BudgetEditView.as_view(), name='budget_edit'),
    path('budget/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget_delete'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api/api-token-auth/', views.obtain_auth_token),
    ]

budget/maapp/urls.py
from django.urls import path
from .views import *
from transactionapp.views import TransactionsListView

app_name = 'maapp'

urlpatterns = [
    path('', AccountsListView.as_view(), name='accounts'),
    path('hide/<int:pk>', AccountsListView.hide_control, name='hide'),
    path('create/', AccountCreateView.as_view(), name='create_account'),
    path('account_<int:pk>/<int:year>/<int:month>/', TransactionsListView.as_view(), name='detail_account'),
]

budget/maapp/models.py
from django.db import models


# Create your models here.
class Currency(models.Model):
    name = models.CharField(verbose_name='название', max_length=3, unique=True)

    def __str__(self):
        return self.name


class MoneyAccount(models.Model):
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    currency = models.ForeignKey(Currency, on_delete=models.RESTRICT)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class MaInfo(models.Model):
    # ma_id = models.BigIntegerField(verbose_name='pk')
    name = models.CharField(verbose_name='название', max_length=64)
    sum = models.DecimalField(verbose_name="сумма", max_digits=10, decimal_places=2)
    is_visible = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'ma_info'

budget/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    error_messages = {
        'duplicate_username': 'Пользователь с таким именем уже существует',
        'duplicate_email': 'Пользователь с таким адресом уже существует',
    }

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User._default_manager.get(username=username)
            raise forms.ValidationError(
                self.error_messages['duplicate_username'],
                code='duplicate_username',
            )
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            User._default_manager.get(email=email)
            raise forms.ValidationError(
                self.error_messages['duplicate_email'],
                code='duplicate_email',
            )
        except User.DoesNotExist:
            return email

budget/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, TemplateView

from budget import settings
from .forms import UserRegisterForm


class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')
    form_class = UserRegisterForm
    success_message = "Your profile was created successfully"

    def form_valid(self, form):
        if self.request.recaptcha_is_valid:
            self.object = form.save()
            return super().form_valid(form)
        return self.render_to_response(self.get_context_data(form=form))

    @receiver(post_save, sender=User)
    def user_to_inactive(sender, instance, created, update_fields, **kwargs):
        if created:
            instance.is_active = False
            mail_subject = 'Activate budget account.'
            message = render_to_string('accounts/email_admin_activation_body.html', {
                'username': instance.username,
                'email': instance.email,
            })
            to_email = settings.EMAIL_HOST_USER
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()


class LoginView(TemplateView):
    success_url = reverse_lazy('index')
    template_name = 'accounts/login.html'

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy(settings.LOGIN_REDIRECT_URL))
            else:
                return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))
        else:
            try:
                user_form = User.objects.get(username=request.POST['username'])
                if not user_form.is_active:
                    messages.error(request, 'Пользователь не активирован')
            except:
                messages.error(request, 'Неверное имя пользователя или пароль')
            return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy(settings.LOGIN_URL))

budget/maapp/views.py
from datetime import datetime

from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from transactionapp.models import Transaction
from .models import MoneyAccount, Currency, MaInfo
from django.db.models import Sum
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView


# Create your views here.


class AccountsListView(ListView):
    template_name = 'maapp/accounts.html'
    model = Transaction

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'счета'
        context['year'] = datetime.now().strftime('%Y')
        context['month'] = datetime.now().strftime('%m')
        return context

    def get_queryset(self):
        # queryset = Transaction.objects. \
        #     select_related('account'). \
        #     filter(past=0). \
        #     values('account__name', 'account__is_visible', 'account'). \
        #     annotate(total_summ=Sum('operation_summ'))
        # for el in queryset:
        #     el['total_summ'] = round(float(el['total_summ']), 2)

        queryset = MaInfo.objects.all().order_by('name')
        # for el in queryset:
        #     if el.sum is None:
        #         el.sum = 0
            # else:
            #     el.sum = round(float(el.sum), 2)
        return queryset

    @staticmethod
    def hide_control(request, pk):
        account = get_object_or_404(MoneyAccount, pk=pk)
        if account.is_visible == 1:
            account.is_visible = 0
        else:
            account.is_visible = 1
        account.save()
        return HttpResponse(200)


class AccountCreateView(CreateView):
    model = MoneyAccount
    template_name = 'maapp/account.html'
    fields = ('name', 'currency')
    success_url = reverse_lazy('money_accounts:accounts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание счёта'
        context['currency'] = Currency.objects.all()
        return context

budget/maapp/templates/maapp/account.html
{% extends 'budget/base.html' %}
{% load static %}
{% block content %}
<body>
<div class="to__bottom">
    <div class="container">
        <div class="title__single">Новый счёт</div>
        <br>
        <br>
        <form method="post">
        {% csrf_token %}
            <input type="text" name="name" class="form__control" placeholder="Название" required>
            <br>
            <h4 class="select__label">Валюта</h4>
            <select name="currency" class="form__select" required>
                {% for el in currency %}
                <option value="{{ el.pk }}">{{ el.name }}</option>
                {% endfor %}
            </select>
            <br>
            <div class="tr__upper tr__upper__left">
                <input type="submit" class="btn btn__green" value="Отправить">
                <input type="button" class="btn btn__red" onclick="window.location.href='{% url 'maapp:accounts' %}';"
                       value="Закрыть">
            </div>
        </form>
    </div>
</div>
</body>
{% endblock %}

budget/maapp/templates/maapp/accounts.html
{% extends 'budget/base.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<body>
    <div class="container">
        <br>
        <div class="title__single">Список счетов</div>
        <br>

        {% comment %}
        {% for object in object_list %}
        <div id="{{ object.account }}" class="double__button {% if object.account__is_visible == 0 %}past__color{% endif %}">
            <div class="name__btn tr__box__acc black__color transparent__color">{{ object.account__name }}</div>
            <a href="{% url 'maapp:detail_account' object.account year month%}"
                class="num tr__box__acc {% if object.total_summ > 0 %}green__color{% else %}red__color{% endif %} transparent__color">{{ object.total_summ|intcomma }}</a>
        </div>
        {% endfor %}
        {% endcomment %}

        {% for object in object_list %}
        <div id="{{ object.id }}" class="double__button {% if object.is_visible == 0 %}past__color{% endif %}">
            <div class="name__btn tr__box__acc black__color transparent__color">{{ object.name }}</div>
            <a href="{% url 'maapp:detail_account' object.id year month%}"
                class="num tr__box__acc {% if object.sum > 0 %}green__color{% else %}red__color{% endif %} transparent__color">{{ object.sum|intcomma }}</a>
        </div>
        {% endfor %}

        <br>
        <div class="single__element__center">
            <a href="{% url 'maapp:create_account' %}" class="footer__button">Добавить счёт</a>
        </div>
        <div class="clear__block"></div>

    </div>
    {% include 'includes/inc_main_menu.html' %}
    <script>

        const btnAccounts = document.querySelectorAll('.name__btn');
        for (let btnAccount of btnAccounts) {
            let accountID = btnAccount.parentNode.id;
            btnAccount.addEventListener('click', () => clickToAccount(accountID));
        }
        async function clickToAccount(accountID) {
            let djangoUrl = "{% url 'maapp:hide' '10' %}"
            let url = djangoUrl.replace('10', accountID)
            let response = await fetch(url);
            const account = document.getElementById(accountID);
            if (!account.classList.contains('past__color')) {
                account.classList.add('past__color');
            } else {
                account.classList.remove('past__color');
            }
        }
    </script>
{#    <script>#}
{#        $('.num').each(function () {#}
{#            this.innerHTML = parseFloat(this.textContent)#}
{#                .toLocaleString('ru-RU')#}
{#        })#}
{#    </script>#}
</body>
{% endblock %}